development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:5a10c649d41b5c63a773ae58cc9cb37f@tarpon.redistogo.com:11705/
  channel_prefix: instatalk_production
